mode: simple_d4j
model_path: /root/autodl-tmp/Model/recoder_ori/best_model.ckpt
ids_path: /root/autodl-tmp/Data/ori_fl.ids
input_dir: /root/autodl-tmp/Data/ori_fl
search_size: 150
classcontent_dir: /root/autodl-tmp/Data/class_content
output_dir: /root/autodl-tmp/Data/d4j_Recoder_ori_fl
valdatapkl_f: /root/autodl-tmp/Model/recoder_ori/valdata.pkl
nl_voc_f: /root/autodl-tmp/Model/recoder_ori/nl_voc.pkl
rule_f: /root/autodl-tmp/Model/recoder_ori/rule.pkl
code_voc_path: /root/autodl-tmp/Model/recoder_ori/code_voc.pkl
char_voc_path: /root/autodl-tmp/Model/recoder_ori/char_voc.pkl
rulead_path: /root/autodl-tmp/Model/recoder_ori/rulead.pkl
NL_voc_size: 41696
code_voc_size: 41696
voc_size: 83
rule_num: 1265
cnum: 764