mode: simple_d4j
model_path: /root/autodl-tmp/Model/best_model.ckpt
ids_path: /root/autodl-tmp/Data/ids.txt
input_dir: /root/autodl-tmp/Data/buggy_methods
search_size: 400
classcontent_dir: /root/autodl-tmp/Data/class_content
output_dir: /root/autodl-tmp/Preds/d4j_Recoder
valdatapkl_f: /root/autodl-tmp/Model/valdata.pkl
nl_voc_f: /root/autodl-tmp/Model/nl_voc.pkl
rule_f: /root/autodl-tmp/Model/rule.pkl
code_voc_path: /root/autodl-tmp/Model/code_voc.pkl
char_voc_path: /root/autodl-tmp/Model/char_voc.pkl
rulead_path: /root/autodl-tmp/Model/rulead.pkl
NL_voc_size: 26167
code_voc_size: 26167
voc_size: 81
rule_num: 1265
cnum: 764