model: /home/zwk/NPR4J_Models/SequenceR/SR_26_step_50000.pt
beam_size: 300
n_best: 300
src: /home/zwk/Processed_Data/SequenceR/vul_buggy.txt
tgt: /home/zwk/Processed_Data/SequenceR/vul_fix.txt
output: /home/zwk/Processed_Data/SequenceR/vul_bugs.pred
gpu: 0
batch_size: 1
batch_type: sents
max_length: 210